// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseCheckboxList: typeof import('./src/components/List/BaseCheckboxList.vue')['default']
    BaseDatePicker: typeof import('./src/components/Form/BaseDatePicker.vue')['default']
    BaseEsign: typeof import('./src/components/Esign/BaseEsign.vue')['default']
    BaseGrid: typeof import('./src/components/Utils/BaseGrid.vue')['default']
    BaseHorizontalGrid: typeof import('./src/components/Utils/BaseHorizontalGrid.vue')['default']
    BasePicker: typeof import('./src/components/Form/BasePicker.vue')['default']
    BaseRadioList: typeof import('./src/components/List/BaseRadioList.vue')['default']
    BaseSearch: typeof import('./src/components/Utils/BaseSearch.vue')['default']
    BaseSwipeList: typeof import('./src/components/Utils/BaseSwipeList.vue')['default']
    BaseTabbar: typeof import('./src/components/Utils/BaseTabbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
